package organisation;
// Generated Feb 27, 2022 11:13:58 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.ManyToAny;

/**
 * Depart generated by hbm2java
 */
public class Depart  implements java.io.Serializable {


     private int DId;
     private String DName;
     private String city;
     @OneToMany(mappedBy = "Depart")
     @Fetch(value=FetchMode.SELECT)
     
     private Set employees = new HashSet(0);

    public Depart() {
    }

	
    public Depart(int DId) {
        this.DId = DId;
    }
    public Depart(int DId, String DName, String city, Set employees) {
       this.DId = DId;
       this.DName = DName;
       this.city = city;
       this.employees = employees;
    }
   
    public int getDId() {
        return this.DId;
    }
    
    public void setDId(int DId) {
        this.DId = DId;
    }
    public String getDName() {
        return this.DName;
    }
    
    public void setDName(String DName) {
        this.DName = DName;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }
    public String toString(){
         return "Department(d_id:"+DId+",D_Name:"+DName+",City:"+city+")";
    }



}


